version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: '11:00'
    timezone: Japan
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 1
  labels:
  - dependencies
  commit-message:
    prefix: deps

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
    time: '11:00'
    timezone: Japan
  commit-message:
    prefix: ci
